### ISSUE TITLE
Weird bug making the SDX unusable

### ISSUE THREAD

**Issue by FloofyWoo** [TheBlackArms/TheBlackArmsSDX#2]
i imported the SDX in unity and thats how it loaded. 
![image](https://user-images.githubusercontent.com/52764294/93952026-da7d3280-fd15-11ea-8cbd-2f4c9ac0e816.png)
![image](https://user-images.githubusercontent.com/52764294/93952058-e963e500-fd15-11ea-84ee-847fbc4885eb.png)
![image](https://user-images.githubusercontent.com/52764294/93952135-1b754700-fd16-11ea-9a0c-f44c0106370c.png)
![image](https://user-images.githubusercontent.com/52764294/93952103-08fb0d80-fd16-11ea-8afc-dbca5934a3da.png)
the button texture is just gone. the first 3 tabs are all login tabs, nothing works, and theres a bunch of werid display bugs.

**Comment by PhoenixAceVFX** [comment]
This is actually really common, I am not sure whats causing this bug but i am heavily looking into it, You can fix this by going to the Settings tab in the control panel and resetting the color, this should only happen on first import from what ive seen, my assumption is that is it because there is not a preset color for it, If my theory is correct this bug should be patched rather quickly.

**Comment by PhoenixAceVFX** [comment]
Issue resolved on Discord via Support Ticket

**Comment by PhoenixAceVFX** [comment]
This bug has been patched, there should no longer be issues relating to this specific bug
